spring:
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10s

id:
  machine-id: 0
  machine-bits: 8
  sequence-bits: 12

tiny-task:
  prefix: tinytask
  timeout: 5

logging:
  level:
    root: info
  file:
    name: /log/tiny-task-spring-boot-starter-test.log
